[package]
name = "fpsdk"
version = "0.1.0"
authors = ["Ales Tsurko <ales.tsurko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
cxx = "0.2"
log = "0.4"

[build-dependencies]
cxx = "0.2"

[dev-dependencies]
log = "0.4"
simplelog = "0.7"
simple-logging = "2.0"

[[example]]
name = "simple"
path = "examples/simple.rs"
crate-type = ["cdylib"]
